### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/micro-agent#12]
integrate with [ollama-js](https://github.com/ollama/ollama-js) for fully local development 

note: in the code there is a [`USE_ASSISTANT`](https://github.com/BuilderIO/micro-agent/blob/main/src/helpers/openai.ts#L14) flag, just treat that as always off (`false`) for ollama as it has no assistants API (also fwiw i don't think the assistants direction is necessary or essential anyway)

in short, you would make sure any call to openai for chat completions goes to ollama-js instead

**Comment by steve8708** [comment]
added it - its pretty dumb/unreliable. highly recommend gpt-4o instead

**Comment by tpaulshippy** [comment]
Curious - what were you seeing that was dumb/unreliable?

**Comment by tpaulshippy** [comment]
Did you try a variety of models? I'm seeing a lot of specialized models for code, like codellama, starcoder2, or codegemma.

[This line](https://github.com/BuilderIO/micro-agent/blob/a3440186660f2be79dbda16ead77cfdcf520833f/src/helpers/llm.ts#L23) indicates maybe not.

**Comment by steve8708** [comment]
I tried only llama3 and phi, models i've had good success with in the past, but definitely would be game for help testing other alternatives

the main "dumb" thing was no matter what, it woudl always output stuff likei this

```
function parse(str: string) {
  const parsed = ts.parse(str);
  // rest of code here
}
```

it would never output the full code and would only output parts of it with "rest of code here" type comments throughout

**Comment by gvzq** [comment]
@steve8708 if you're hardware is good enough you can get some neat results. For example, the [mixtral:8x22b](https://ollama.com/library/mixtral:8x22b) with Ollama might be used to override the openai endpoints locally. 

```bash
endpoint=http://localhost:11434/v1/
model=mixtral:8x22b
key=ollama
```
Alternatively, Groq's mixtral-8x7b-32768 has amazing speeds and a huge context window. 

```bash
endpoint=https://api.groq.com/openai/v1
model=mixtral-8x7b-32768
key=gsk_KEY
```

My code generated generated perfectly but failed at GET /openai/v1/assistants. 👎

**Comment by steve8708** [comment]
ah! just pushed a fix for that. try version 0.1.1 and use `micro-agent config` to change `USE_ASSISTANT` to `false`

**Comment by steve8708** [comment]
perhaps in a future version we should just automatically turn assistants off  if a custom endpoint is used 🤔

**Comment by steve8708** [comment]
yeah i'll just turn assistant off anytime an endpoint is used ✅

**Comment by gvzq** [comment]
@steve8708 you're moving at lightning speeds. It's working now and thank you for this project.

**Comment by AlonJoshua** [comment]
> yeah i'll just turn assistant off anytime an endpoint is used ✅

Hey @steve8708 have you already updated this behavior in the package?

Right now config set USE_ASSISTANT=false works only when playing with micro-agent project locally:
<img width="597" alt="Screenshot 2024-06-23 at 12 44 09" src="https://github.com/BuilderIO/micro-agent/assets/52909700/dc66f967-b57b-4cc7-9b57-74bf31f4c24c">

But doesn't recognize that config when using micro-agent package:
<img width="637" alt="Screenshot 2024-06-23 at 12 47 04" src="https://github.com/BuilderIO/micro-agent/assets/52909700/2d9a04e1-f0d1-4b65-abed-2a907914a978">

**Comment by steve8708** [comment]
ah, i may have not released recently enough! I'll push a release now

**Comment by steve8708** [comment]
release done, try `0.1.3` (e.g. via running `micro-agent update`). still see the issue with that?

**Comment by AlonJoshua** [comment]
The issue is fixed, thanks!
