### ISSUE TITLE
Question: is possible to add Ollama support?

### ISSUE THREAD

**Issue by velteyn** [BuilderIO/micro-agent#32]
Hi , great project here. I would like to ask if it is possible to have Ollama support fo local LLMs like Mistral Instruct 8b that can run in a laptop. Thz

**Comment by tpaulshippy** [comment]
See https://github.com/BuilderIO/micro-agent/issues/12

Should already have it to some extent although may need to add support for more models.

**Comment by gvzq** [comment]
@velteyn here the config that worked for me.

Run `micro-agent config` and set all the option with the following: 

```bash
endpoint=http://localhost:11434/v1/
model=mixtral:8x7b
key=ollama
```
