### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by pothuraju-dev** [BuilderIO/micro-agent#44]
It worked fine till I try to change config for using groq through OpenAI_Endpoint

![image](https://github.com/BuilderIO/micro-agent/assets/59384635/d092711d-ea11-4678-b4e7-4c4f50af9752)

**Comment by steve8708** [comment]
what did you use as the config value?

**Comment by pothuraju-dev** [comment]
> what did you use as the config value?

groq token and endpoint as 'groq'

**Comment by steve8708** [comment]
the endpoint needs to be a URL. For Groq it would be `https://api.groq.com/openai/v1`

**Comment by pothuraju-dev** [comment]
> the endpoint needs to be a URL. For Groq it would be `https://api.groq.com/openai/v1`

Thanks, I will check
