### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by jgansl** [BuilderIO/micro-agent#47]
(node:27484) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Mac Apple Silicon M1 Max
Sonoma 14.5 (23F79)
Node 22.3
NPM 10.8

**Comment by steve8708** [comment]
should be fixed in 0.1.5 - if you still see it after that version lmk
