### ISSUE TITLE
Question: Does it ony work for JavaScript projects?

### ISSUE THREAD

**Issue by sprklinginfo** [BuilderIO/micro-agent#53]
It looks like it only works for JavaScript projects, right? Like react or angular?

**Comment by natsu12** [comment]
When using micro-agent in a python project, a prompt will be reported: "Warning: The current directory does not appear to be a recognized project folder.Want to set up a new project?" And only "Node + Vitest project" can be selected. How can I use it in a python project?

**Comment by steve8708** [comment]
oh its supposed to detect a requirements.txt file to identify the project as a python project, do you have a requirements.txt file at the root of your project?

**Comment by sprklinginfo** [comment]
maybe I should be specific: can I use it for PHP projects, e.g. Laravel projects?

**Comment by tpaulshippy** [comment]
I don't believe php is currently supported. @steve8708 is pretty good about accepting PRs quickly so I would recommend submitting one to add this. If you need help finding where to add this support let me know (I worked on the python and ruby support).
